<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <NoWarn>$(NoWarn);SYSLIB5001;SYSLIB5002;SYSLIB5003;SYSLIB5004;SYSLIB5005;SYSLIB5006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="ObjectLayoutInspector" Version="0.1.4" />
    <!--PackageReference Include="System.IO.Hashing" Version="11.0.0-preview.1.26104.118" /-->
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>
</Project>
